apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- provider-components-openstack-clouds-secrets.yaml
- provider-components-kubeadm.yaml
- provider-components-cluster-api.yaml
- provider-components-openstack.yaml
patchesStrategicMerge:
- manager_tolerations_patch.yaml
