linters:
  enable-all: true
  disable:
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godox
    - gomnd
    - lll
    - maligned
    - whitespace
    - wsl
  # Run with --fast=false for more extensive checks
  fast: true
linters-settings:
  goimports:
    local-prefixes: sigs.k8s.io/cluster-api-provider-openstack
issues:
  max-same-issues: 0
  max-per-linter: 0
  # List of regexps of issue texts to exclude, empty list by default.
  exclude:
    - Using the variable on range scope `(tc)|(rt)|(tt)|(test)|(testcase)|(testCase)` in function literal
    - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
run:
  timeout: 6m
  skip-files:
    - "zz_generated.*\\.go$"
    - ".*_mock\\.go"
