# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1800s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
# To check if the image can handle the build, you can try it like this:
# docker run --rm -it -v $(pwd):/workspace gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:${TAG}
# make clean # make sure we have something to build
# make staging-manifests
- name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20250116-2a05ea7e3d'
  entrypoint: make
  env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - TAG=$_GIT_TAG
  - PULL_BASE_REF=$_PULL_BASE_REF
  - DOCKER_BUILDKIT=1
  args:
  - release-staging
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'
