# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-capo-vars
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  serveOldVersions: false
  webhookServiceCert: capo-webhook-service-cert
