apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: openstackproviderspecs.openstackproviderconfig.k8s.io
spec:
  group: openstackproviderconfig.k8s.io
  names:
    kind: OpenstackProviderSpec
    plural: openstackproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        availabilityZone:
          type: string
        cloudName:
          type: string
        cloudsSecret:
          type: object
        configDrive:
          type: boolean
        flavor:
          type: string
        floatingIP:
          type: string
        image:
          type: string
        keyName:
          type: string
        kind:
          type: string
        metadata:
          type: object
        networks:
          items:
            properties:
              filter:
                properties:
                  description:
                    type: string
                  adminStateUp:
                    type: boolean
                  id:
                    type: string
                  limit:
                    format: int64
                    type: integer
                  marker:
                    type: string
                  name:
                    type: string
                  notTags:
                    type: string
                  notTagsAny:
                    type: string
                  projectId:
                    type: string
                  shared:
                    type: boolean
                  sortDir:
                    type: string
                  sortKey:
                    type: string
                  status:
                    type: string
                  tags:
                    type: string
                  tagsAny:
                    type: string
                  tenantId:
                    type: string
                type: object
              fixedIp:
                type: string
              subnets:
                items:
                  properties:
                    filter:
                      properties:
                        cidr:
                          type: string
                        description:
                          type: string
                        id:
                          type: string
                        enableDhcp:
                          type: boolean
                        ipVersion:
                          format: int64
                          type: integer
                        limit:
                          format: int64
                          type: integer
                        marker:
                          type: string
                        name:
                          type: string
                        tags:
                          type: string
                        networkId:
                          type: string
                        notTags:
                          type: string
                        notTagsAny:
                          type: string
                        projectId:
                          type: string
                        sortDir:
                          type: string
                        sortKey:
                          type: string
                        subnetpoolId:
                          type: string
                        tags:
                          type: string
                        tagsAny:
                          type: string
                        tenantId:
                          type: string
                      type: object
                    uuid:
                      type: string
                  type: object
                type: array
              uuid:
                type: string
            type: object
          type: array
        securityGroups:
          items:
            properties:
              filter:
                properties:
                  description:
                    type: string
                  id:
                    type: string
                  limit:
                    format: int64
                    type: integer
                  marker:
                    type: string
                  name:
                    type: string
                  notTags:
                    type: string
                  notTagsAny:
                    type: string
                  projectId:
                    type: string
                  sortDir:
                    type: string
                  sortKey:
                    type: string
                  tags:
                    type: string
                  tagsAny:
                    type: string
                  tenantId:
                    type: string
                type: object
              name:
                type: string
              uuid:
                type: string
            type: object
          type: array
        serverMetadata:
          type: object
        sshUserName:
          type: string
        tags:
          items:
            type: string
          type: array
        trunk:
          type: boolean
        userDataSecret:
          type: object
      required:
      - cloudsSecret
      - cloudName
      - flavor
      - image
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
