apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: openstackclusterproviderspecs.openstackproviderconfig.k8s.io
spec:
  group: openstackproviderconfig.k8s.io
  names:
    kind: OpenstackClusterProviderSpec
    plural: openstackclusterproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiServerLoadBalancerAdditionalPorts:
          description: APIServerLoadBalancerAdditionalPorts adds additional ports
            to the APIServerLoadBalancer
          items:
            format: int64
            type: integer
          type: array
        apiServerLoadBalancerFloatingIP:
          description: APIServerLoadBalancerFloatingIP is the floatingIP which will
            be associated to the APIServer loadbalancer. The floatingIP will be created
            if it not already exists.
          type: string
        apiServerLoadBalancerPort:
          description: APIServerLoadBalancerPort is the port on which the listener
            on the APIServer loadbalancer will be created
          format: int64
          type: integer
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        caKeyPair:
          description: CAKeyPair is the key pair for ca certs.
          properties:
            cert:
              description: base64 encoded cert and key
              format: byte
              type: string
            key:
              format: byte
              type: string
          type: object
        cloudName:
          description: The name of the cloud to use from the clouds secret
          type: string
        cloudsSecret:
          description: The name of the secret containing the openstack credentials
          type: object
        disableServerTags:
          description: 'Default: True. In case of server tag errors, set to False'
          type: boolean
        dnsNameservers:
          description: DNSNameservers is the list of nameservers for OpenStack Subnet
            being created.
          items:
            type: string
          type: array
        etcdCAKeyPair:
          description: EtcdCAKeyPair is the key pair for etcd.
          properties:
            cert:
              description: base64 encoded cert and key
              format: byte
              type: string
            key:
              format: byte
              type: string
          type: object
        externalNetworkId:
          description: ExternalNetworkID is the ID of an external OpenStack Network.
            This is necessary to get public internet to the VMs.
          type: string
        externalRouterIPs:
          description: ExternalRouterIPs is an array of externalIPs on the respective
            subnets. This is necessary if the router needs a fixed ip in a specific
            subnet.
          items:
            properties:
              fixedIP:
                description: The FixedIP in the corresponding subnet
                type: string
              subnet:
                description: The subnet in which the FixedIP is used for the Gateway
                  of this router
                properties:
                  filter:
                    description: Filters for optional network query
                    properties:
                      cidr:
                        type: string
                      description:
                        type: string
                      enableDhcp:
                        type: boolean
                      id:
                        type: string
                      ipVersion:
                        format: int64
                        type: integer
                      ipv6AddressMode:
                        type: string
                      ipv6RaMode:
                        type: string
                      limit:
                        format: int64
                        type: integer
                      marker:
                        type: string
                      name:
                        type: string
                      networkId:
                        type: string
                      notTags:
                        type: string
                      notTagsAny:
                        type: string
                      projectId:
                        type: string
                      sortDir:
                        type: string
                      sortKey:
                        type: string
                      subnetpoolId:
                        type: string
                      tags:
                        type: string
                      tagsAny:
                        type: string
                      tenantId:
                        type: string
                    type: object
                  uuid:
                    description: The UUID of the network. Required if you omit the
                      port attribute.
                    type: string
                type: object
            required:
            - subnet
            type: object
          type: array
        frontProxyCAKeyPair:
          description: FrontProxyCAKeyPair is the key pair for FrontProxyKeyPair.
          properties:
            cert:
              description: base64 encoded cert and key
              format: byte
              type: string
            key:
              format: byte
              type: string
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        managedAPIServerLoadBalancer:
          description: 'ManagedAPIServerLoadBalancer defines whether a LoadBalancer
            for the APIServer should be created. If set to true the following properties
            are mandatory: APIServerLoadBalancerFloatingIP, APIServerLoadBalancerPort'
          type: boolean
        managedSecurityGroups:
          description: ManagedSecurityGroups defines that kubernetes manages the OpenStack
            security groups for now, that means that we'll create two security groups,
            one allowing SSH and API access from everywhere, and another one that
            allows all traffic to/from machines belonging to that group. In the future,
            we could make this more flexible.
          type: boolean
        masterIP:
          description: MasterIP is the ip of the master, if there is Loadbalancer,
            should be LB ip and no LB should be floating ip address
          type: string
        metadata:
          type: object
        nodeCidr:
          description: NodeCIDR is the OpenStack Subnet to be created. Cluster actuator
            will create a network, a subnet with NodeCIDR, and a router connected
            to this subnet. If you leave this empty, no network will be created.
          type: string
        saKeyPair:
          description: SAKeyPair is the service account key pair.
          properties:
            cert:
              description: base64 encoded cert and key
              format: byte
              type: string
            key:
              format: byte
              type: string
          type: object
        tags:
          description: Tags for all resources in cluster
          items:
            type: string
          type: array
      required:
      - cloudsSecret
      - cloudName
      - managedAPIServerLoadBalancer
      - managedSecurityGroups
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
