apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: openstackclusterproviderstatuses.openstackproviderconfig.k8s.io
spec:
  group: openstackproviderconfig.k8s.io
  names:
    kind: OpenstackClusterProviderStatus
    plural: openstackclusterproviderstatuses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        controlPlaneSecurityGroup:
          properties:
            id:
              type: string
            name:
              type: string
            rules:
              items:
                properties:
                  direction:
                    type: string
                  etherType:
                    type: string
                  name:
                    type: string
                  portRangeMax:
                    format: int64
                    type: integer
                  portRangeMin:
                    format: int64
                    type: integer
                  protocol:
                    type: string
                  remoteGroupID:
                    type: string
                  remoteIPPrefix:
                    type: string
                  securityGroupID:
                    type: string
                required:
                - name
                - direction
                - etherType
                - securityGroupID
                - portRangeMin
                - portRangeMax
                - protocol
                - remoteGroupID
                - remoteIPPrefix
                type: object
              type: array
          required:
          - name
          - id
          - rules
          type: object
        globalSecurityGroup:
          properties:
            id:
              type: string
            name:
              type: string
            rules:
              items:
                properties:
                  direction:
                    type: string
                  etherType:
                    type: string
                  name:
                    type: string
                  portRangeMax:
                    format: int64
                    type: integer
                  portRangeMin:
                    format: int64
                    type: integer
                  protocol:
                    type: string
                  remoteGroupID:
                    type: string
                  remoteIPPrefix:
                    type: string
                  securityGroupID:
                    type: string
                required:
                - name
                - direction
                - etherType
                - securityGroupID
                - portRangeMin
                - portRangeMax
                - protocol
                - remoteGroupID
                - remoteIPPrefix
                type: object
              type: array
          required:
          - name
          - id
          - rules
          type: object
        kind:
          type: string
        metadata:
          type: object
        network:
          properties:
            id:
              type: string
            name:
              type: string
            router:
              properties:
                id:
                  type: string
                name:
                  type: string
              required:
              - name
              - id
              type: object
            subnet:
              properties:
                cidr:
                  type: string
                id:
                  type: string
                name:
                  type: string
              required:
              - name
              - id
              - cidr
              type: object
          required:
          - name
          - id
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
