apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  name: test-cluster-kube-master-01
  labels:
    cluster.x-k8s.io/cluster-name: test-cluster
    cluster.x-k8s.io/control-plane: "true"
spec:
  bootstrap:
    configRef:
      kind: KubeadmConfig
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      namespace: default
      name: test-cluster-config
  infrastructureRef:
    kind: OpenStackMachine
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    namespace: default
    name: test-cluster-kube-master-01
  version: "1.15.0"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: OpenStackMachine
metadata:
  name: test-cluster-kube-master-01
spec:
  cloudName: <Cloud Name>
  flavor: m1.medium
  image: <Image Name>
  keyName: cluster-api-provider-openstack
  availabilityZone: nova
  networks:
  - uuid: <Kubernetes Network ID>
  floatingIP: <Available Floating IP>
  securityGroups:
  - uuid: <Security Group ID>
  userDataSecret:
    name: master-user-data
    namespace: openstack-provider-system
  trunk: false
  tags:
    - a-machine-specific-tag
  serverMetadata:
    key: value
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: test-cluster-config
spec:
  clusterConfiguration:
    certificatesDir: /etc/kubernetes/pki
    controlPlaneEndpoint: <End point Ip: End point Address>
    dns:
      type: "CoreDNS"
    imageRepository: "k8s.gcr.io"
    kubernetesVersion: 1.15.0
    networking:
      dnsDomain: ""
      podSubnet: ""
      serviceSubnet: ""
    etcd: {}
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  name: test-cluster-openstack-node-01
  labels:
    cluster.x-k8s.io/cluster-name: test-cluster
spec:
  bootstrap:
    configRef:
      kind: KubeadmConfig
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      namespace: default
      name: test-cluster-config
  infrastructureRef:
    kind: OpenStackMachine
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    namespace: default
    name: test-cluster-openstack-node-01
  version: "1.15.0"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: OpenStackMachine
metadata:
  name: test-cluster-openstack-node-01
spec:
  cloudName: <Cloud Name>
  flavor: m1.medium
  image: <Image Name>
  keyName: cluster-api-provider-openstack
  availabilityZone: nova
  networks:
  - uuid: <Kubernetes Network ID>
  floatingIP: <Available Floating IP>
  securityGroups:
  - uuid: <Security Group ID>
  userDataSecret:
    name: worker-user-data
    namespace: openstack-provider-system
  trunk: false
  tags:
    - a-machine-specific-tag
  serverMetadata:
    key: value
