apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster.yaml
patchesStrategicMerge:
- e2e-conformance_patch.yaml
patchesJSON6902:
# sets the password of the capo user to capo
- target:
      group: bootstrap.cluster.x-k8s.io
      version: v1alpha3
      kind: KubeadmConfigTemplate
      name: capi-quickstart-md-0
  patch: |-
      - op: replace
        path: /spec/template/spec/users/0/passwd
        value: '$1$SaltSalt$JQx8irEe3sMOl/Lu8y7oZ1'
- target:
      group: controlplane.cluster.x-k8s.io
      version: v1alpha3
      kind: KubeadmControlPlane
      name: capi-quickstart-control-plane
  patch: |-
      - op: replace
        path: /spec/kubeadmConfigSpec/users/0/passwd
        value: '$1$SaltSalt$JQx8irEe3sMOl/Lu8y7oZ1'
