apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstack-provider-manager-secrets
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstack-provider-manager-secrets
subjects:
- kind: ServiceAccount
  name: default
  namespace: openstack-provider-system
