---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"] # CIDR block used by Calico.
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: OpenStackCluster
    name: ${CLUSTER_NAME}
    namespace: ${CLUSTER_NAME}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: "${CLUSTER_NAME}-control-plane"
    namespace: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${CLUSTER_NAME}
spec:
  cloudName: $CLOUD
  cloudsSecret:
    name: cloud-config
    namespace: ${CLUSTER_NAME}
  nodeCidr: ${NODE_CIDR}
  managedAPIServerLoadBalancer: true
  apiServerLoadBalancerFloatingIP: ${CONTROLPLANE_FLOATING_IP}
  apiServerLoadBalancerPort: 6443
  apiServerLoadBalancerAdditionalPorts:
  - 22
  dnsNameservers: []
  # multi-node control-plane:
  # * externalNetworkId is required for:
  #   * creating routers
  #   * creating floating ips
  #   * creating load balancer
  externalNetworkId: ${EXTERNAL_NETWORK_ID}
  disablePortSecurity: true
  disableServerTags: true
  useOctavia: true
