<<<<<<< HEAD
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-cluster-api-openstack
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: CloudCredential
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
  secretRef:
    name: openstack-cloud-credentials
    namespace: openshift-cluster-api
||||||| parent of b907b2097 (Add cluster-capi-operator integration)
=======
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-cluster-api-openstack
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: CloudCredential
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
  secretRef:
    name: openstack-cloud-credentials
    namespace: openshift-cluster-api
>>>>>>> b907b2097 (Add cluster-capi-operator integration)
