apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
# Remove any cert-manager annotations
- target:
    annotationSelector: cert-manager.io/inject-ca-from
  patch: |-
    - op: remove
      path: "/metadata/annotations/cert-manager.io~1inject-ca-from"

# Don't emit any cert-manager assets
- target:
    group: cert-manager.io
    version: v1
  patch: |-
    $patch: delete
    apiversion: ignored
    kind: ignored
    metadata:
      name: ignored

# To avoid SSA conflicts, don't set caBundle for conversion webhooks: service-ca-operator will inject it
- target:
    kind: CustomResourceDefinition
  patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: ignored
    spec:
      conversion:
        webhook:
          clientConfig:
            caBundle:

# Set service-ca inject-cabundle annotation on api objects for webhooks
- target:
    kind: CustomResourceDefinition
  patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: ignored
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
- target:
    kind: ValidatingWebhookConfiguration
  patch: |-
    apiVersion: v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: ignored
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
- target:
    kind: MutatingWebhookConfiguration
  patch: |-
    apiVersion: v1
    kind: MutatingWebhookConfiguration
    metadata:
      name: ignored
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
