apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: openshift-cluster-api

resources:
- vars.yaml

commonAnnotations:
  exclude.release.openshift.io/internal-openshift-hosted: "true"
  include.release.openshift.io/self-managed-high-availability: "true"
  include.release.openshift.io/single-node-developer: "true"

patches:
# Replace cert-manager cert injection with openshift cert injection in all objects
- target:
    annotationSelector: cert-manager.io/inject-ca-from
  patch: |-
    - op: remove
      path: "/metadata/annotations/cert-manager.io~1inject-ca-from"
    - op: add
      path: "/metadata/annotations/service.beta.openshift.io~1inject-cabundle"
      value: true

# Common configuration for CAPI controller workloads
- target:
    group: apps
    version: v1
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ignored
    spec:
      template:
        annotations:
          # https://github.com/openshift/enhancements/blob/master/enhancements/workload-partitioning/wide-availability-workload-partitioning.md
          target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        spec:
          priorityClassName: "system-cluster-critical"

# Don't call conversion webhooks
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: remove
      path: /spec/conversion

replacements:
# Set resources and limits on all containers
# https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits
- source:
    version: v1
    kind: ConfigMap
    name: kustomize-capi-vars
    fieldPath: data.controllerResources
  targets:
  - select:
      group: apps
      version: v1
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.*.resources
    options:
      create: true
