# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-capi-vars
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  controllerResources:
    requests:
      cpu: 10m
      memory: 50Mi
