---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infracluster-controller
  labels:
    control-plane: capo-infracluster-controller
spec:
  selector:
    matchLabels:
      control-plane: capo-infracluster-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: capo-infracluster-controller
    spec:
      containers:
        - command:
          - /infracluster-controller
          args:
            - "--leader-elect"
            - "--metrics-bind-address=127.0.0.1:8080"
            - "--zap-log-level=2"
          image: controller:latest
          imagePullPolicy: Always
          name: manager
          ports:
            - containerPort: 8081
              name: healthz
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            runAsUser: 65532
            runAsGroup: 65532
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: infracluster-controller
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
