apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- role_binding.yaml
- role.yaml
- service_account.yaml
- leader_election_role_binding.yaml
- controller.yaml

components:
- ../components/namespaced
