apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infracluster-controller-leader-election-rolebinding
# This role is created by infrastructure-components 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capo-leader-election-role
subjects:
- kind: ServiceAccount
  name: infracluster-controller
