---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infracluster-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infracluster-controller
subjects:
- kind: ServiceAccount
  name: infracluster-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infracluster-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infracluster-controller
subjects:
- kind: ServiceAccount
  name: infracluster-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infracluster-controller-rolebinding
  namespace: openshift-machine-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infracluster-controller
subjects:
- kind: ServiceAccount
  name: infracluster-controller
  namespace: openshift-cluster-api
