#####################################################
# ${CLUSTER_NAME}-controlplane
#####################################################
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: "${CLUSTER_NAME}-control-plane"
  namespace: ${CLUSTER_NAME}
spec:
  replicas: 1
  infrastructureTemplate:
    kind: OpenStackMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    name: "${CLUSTER_NAME}-control-plane"
  kubeadmConfigSpec:
    initConfiguration:
      localAPIEndpoint:
        advertiseAddress: '{{ ds.ec2_metadata.local_ipv4 }}'
        bindPort: 6443
      nodeRegistration:
        name: '{{ local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: openstack
          cloud-config: /etc/kubernetes/cloud.conf
    clusterConfiguration:
      controlPlaneEndpoint: "${CONTROLPLANE_FLOATING_IP}:6443"
      imageRepository: k8s.gcr.io
      apiServer:
        extraArgs:
          cloud-provider: openstack
          cloud-config: /etc/kubernetes/cloud.conf
        extraVolumes:
        - name: cloud
          hostPath: /etc/kubernetes/cloud.conf
          mountPath: /etc/kubernetes/cloud.conf
          readOnly: true
      controllerManager:
        extraArgs:
          cloud-provider: openstack
          cloud-config: /etc/kubernetes/cloud.conf
        extraVolumes:
        - name: cloud
          hostPath: /etc/kubernetes/cloud.conf
          mountPath: /etc/kubernetes/cloud.conf
          readOnly: true
        - name: cacerts
          hostPath: /etc/certs/cacert
          mountPath: /etc/certs/cacert
          readOnly: true
    joinConfiguration:
      nodeRegistration:
        name: '{{ local_hostname }}'
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
    files:
    - path: /etc/kubernetes/cloud.conf
      owner: root
      permissions: "0600"
      content: |-
        # cloud.conf to communicate with OpenStack
        $OPENSTACK_CLOUD_PROVIDER_CONF8
    - path: /etc/certs/cacert
      owner: root
      permissions: "0600"
      content: |
        $OPENSTACK_CLOUD_CACERT_CONFIG8
    ntp:
      servers: []
    users:
    - name: capo
      sudo: "ALL=(ALL) NOPASSWD:ALL"
      sshAuthorizedKeys:
      - "$MACHINE_CONTROLLER_SSH_PUBLIC_FILE_CONTENT"

  version: "${KUBERNETES_VERSION}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: ${CLUSTER_NAME}
spec:
  template:
    spec:
      flavor: m1.medium
      image: ${OS_IMAGE_NAME}
      availabilityZone: ${AVAILABILITY_ZONE}
      floatingIP: ${CONTROLPLANE_FLOATING_IP}
      cloudName: $CLOUD
      cloudsSecret:
        name: cloud-config
        namespace: ${CLUSTER_NAME}
